### ISSUE TITLE
SugarORM doesn't work with multi-dex

### ISSUE THREAD

**Issue by gauchito** [satyan/sugar#267]
I have a project which uses SugarORM and it was working fine until I enabled multi-dex. After that I've noticed that sometimes the app doesn't create all the db tables in the device. I suspect it's because when it loads dynamically the domain classes, it only picks up the ones in classes.dex and not in the other dex files. So if unfortunately the domain classes are packed in classes2.dex for example, then the db tables for them are not created during start up.

**Comment by whoshuu** [comment]
Have you tried setting the domain classes field in the manifest? Set it to the topmost package name for the set of models you want to persist. See here:

https://github.com/satyan/sugar/blob/1f49d7c9bfabe72bdcbb02f7639d38d8aee27756/library/src/main/java/com/orm/util/ManifestHelper.java#L21

**Comment by gauchito** [comment]
Hi. Thanks for your reply. I already have that field in the manifest indeed. One thing I noticed is that I'm using release 1.3 from maven repository, but it´s a one year old jar with 145 commits behind master. Do you think this bug might be fixed in master already? Why isn't there a new version released? Any known bug in master? I'd prefer to use gradle dependency rather that library project.

**Comment by whoshuu** [comment]
Give it a test with the master branch and let me know if this bug persists. If it does, I'll do a deeper dive and try to get to the bottom of it.

I understand a gradle dependency is the preferred way of grabbing the library. Unfortunately I believe @satyan is away right now, and he's the only one with write access to maven central for this library.

**Comment by tracytheron** [comment]
does this bug has been fixed now? I met the same issue that Sugar cannot create all tables when I enable multi-dex.

**Comment by bendaniel10** [comment]
I ran into this issue too, I found out that when MultiDex is enabled, the ReflectionUtil class does not scan all the dex files for entity classes correctly, I think it scans the first one only. I've forked the project and provided a fix for that: https://github.com/bendaniel10/sugar

**Comment by tracytheron** [comment]
@bendaniel10 yes, that's the issue. I fixed it few months ago, but @satyan perhaps is away. https://github.com/satyan/sugar/pull/327

**Comment by Vookash** [comment]
Is it fixed? I have version 1.4 and still have this problem.

**Comment by sibeliusseraphini** [comment]
@bendaniel10 could you provide a pull request to fix this?
