### ISSUE TITLE
Upgraded to Android Studio 2.0 - Tables won't create

### ISSUE THREAD

**Issue by tracerstevens** [satyan/sugar#572]
I just upgraded to Android Studio 2.0 and now when I compile it says that my tables don't exist.  It looks like it's not creating my tables.  Can you help?

**Comment by JonatanSalas** [comment]
The problem is with Android Studio InstantRun feature. You have two options:
- You disable InstantRun and then it will work
- You use the branch master of Sugar, because it has been solved by PR #564

**Comment by tracerstevens** [comment]
Sounds good, I turned off instant run and was still getting the issue but it's because I hadn't fully uninstalled the previous installation.

Thanks for the very quick response!

**Comment by JonatanSalas** [comment]
You are welcome! :)
