### ISSUE TITLE
Android Studio 3.2.1 DB is no longer created

### ISSUE THREAD

**Issue by hamada147** [satyan/sugar#809]
As of Android Studio 3.2.1 DB is no longer created even with instant run disabled. Please advice.

**Comment by MohamedMks** [comment]
I fixed same problem by cleaning android studio  cache (in users/username folder delete .gradle folder and .android ) no need to delete settings folder , hope it helps

**Comment by hamada147** [comment]
I will test it today and get back to you.

**Comment by hamada147** [comment]
@MohamedMks 
I've tried it many times it is not working. I even made a whole new project it is still not making the DB nor the tables.

**Comment by hamada147** [comment]
@MohamedMks 
I created a third project and it now works with no issues.
